/**
 * DO NOT EDIT!
 * This file was autogenerated by Carson.
 * Changes may cause incorrect behavior and will be lost when the file is regenerated.
 *
 * Run `npx carson update workspace` to regenerate.
 */

import main, {nodejs, prettier} from '@jakubmazanec/eslint-config';

export default [
  ...main,
  ...nodejs,
  ...prettier,
  {
    ignores: [
      '**/*.d.ts',
      '**/*.json',
      '**/*.md',
      '**/*.mdx',
      '.cache/**',
      '.turbo/**',
      'bin/**',
      'build/**',
      'coverage/**',
      'node_modules/**',
      'public/**',
      '.react-router/**',
    ],
  },
  {
    ignores: ['$/**', 'assets/**'],
  },
  {
    rules: {
      'unicorn/prefer-dom-node-remove': 'off',
    },
  },
  {
    files: ['**/*.{js,jsx,cjs,mjs,ts,tsx,cts,mts}'],
    rules: {
      '@stylistic/js/lines-around-comment': [
        'error',
        {
          beforeBlockComment: true,
          allowClassStart: true,
          allowTypeStart: true,
        },
      ],
      'perfectionist/sort-classes': [
        'error',
        {
          type: 'alphabetical',
          ignoreCase: false,
          groups: [
            'property',
            'private-property',
            'static-property',
            'static-block',
            'constructor',
            'static-method',
            ['get-method', 'set-method'],
            ['method', 'function-property'],
            ['private-method', 'private-function-property'],
            'unknown',
          ],
        },
      ],
      '@stylistic/js/padding-line-between-statements': [
        'error',
        {
          blankLine: 'always',
          prev: '*',
          next: 'continue',
        },
        {
          blankLine: 'always',
          prev: '*',
          next: 'break',
        },
        {
          blankLine: 'always',
          prev: '*',
          next: 'return',
        },
        {
          blankLine: 'always',
          prev: 'import',
          next: '*',
        },
        {
          blankLine: 'any',
          prev: 'import',
          next: 'import',
        },
        {
          blankLine: 'always',
          prev: ['const', 'let', 'var'],
          next: '*',
        },
        {
          blankLine: 'always',
          prev: '*',
          next: ['const', 'let', 'var'],
        },
        {
          blankLine: 'never',
          prev: ['const', 'let', 'var'],
          next: ['const', 'let', 'var'],
        },
        {
          blankLine: 'always',
          prev: 'if',
          next: '*',
        },
        {
          blankLine: 'always',
          prev: '*',
          next: 'if',
        },
        {
          blankLine: 'always',
          prev: 'if',
          next: 'if',
        },
      ],
    },
  },
];
