/**
 * DO NOT EDIT!
 * This file was autogenerated by Carson.
 * Changes may cause incorrect behavior and will be lost when the file is regenerated.
 *
 * Run `npx carson update workspace` to regenerate.
 */

import {type Config} from '@react-router/dev/config';
import _ from 'lodash';

export default _.merge(
  {
    appDirectory: 'source',
    ssr: true,
  },
  {},
) satisfies Config;
